### ISSUE TITLE
New version seems stable

### ISSUE THREAD

**Issue by ghost** [Killface1980/RW_ColonistBarKF#1]
Been 12 days since a change, I haven't come across any issues with it, make it the new release?

**Comment by tommargar** [comment]
need to modify the menu;
1. add options "show weapon icon" (minor).
2. add dropdown list for sorting.
3. I can sort by gender, age, or health. and also in combination. but all combinations need to be defined saparately. I'd need some sorting like Lightroom has http://digital-photography-school.com/wp-content/uploads/2010/08/lightroom-filters-smart-collections-2.png
   with first x then y then z to make it properly

as I was mostly doing other stuff the last days, this is yet to be done

**Comment by tommargar** [comment]
will be released for A15 once CCCL is updated
