### ISSUE TITLE
Current work icons

### ISSUE THREAD

**Issue by tommargar** [Killface1980/RW_ColonistBarKF#10]
Would it be possible to include a set of icons for tasks being done by the pawns?

If so, I'd suggest putting then as an overlay in the top right corner of each pawns' portrait, just above the square which indicates weapons carried.

**Comment by XedMada** [comment]
If you'd like any help with the icons for this please let me know. I have a massive collection of open license 2-bit vector icons to make the assets with if you have a list of the activities to pair them up with.

**Comment by tommargar** [comment]
hi, Xed, feeling honoured for your offer. I haven't really thought about work icons, so nothing created yet. your icon collection sounds promising, if you want to make a pre-selection you can head over to the file "WorkGivers.xml" in the Mods/Core/Defs/WorkGiverDefs folder. All vanilla work types are listed here. But I think I'll add missing icons first (like imprisoned, or cabin fever), and improve visibility. Adding the work icons should be no big deal. Thanks again!

**Comment by tommargar** [comment]
added tooltip with current job description on hovering over colonist in bar
