### ISSUE TITLE
even with massive icons you can't really tell the weapon

### ISSUE THREAD

**Issue by tommargar** [Killface1980/RW_ColonistBarKF#13]
2: Weapon icons let you know if people have weapons but that's about it, even with massive icons you can't really tell the weapon. Having an option to have a very large gun icon would be nice in addition to the small ones. Default could be on the weapon on the right hand side pointing up with the gun/weapon texture overlaying the pawn box with no border. And long guns stretch all the way across. I request this because I'm not one who needs to know my pawns are armed, I have never had a bad event without someone armed, I'm on day 700 or so. My point is the weapon icon is useless to me, thus this would give the icon purpose, aesthetics.

**Comment by lclpsoz** [comment]
One way would be to create simpler icons. Something 4 generic textures (guns, grenades, blunt weapons and sharp weapons). Theses textures would be easier to recognize even in small size, like the _mood icons_ from this mod.

**Comment by tommargar** [comment]
I've added a tooltip when hovering above the icon a while ago.
