### ISSUE TITLE
PSI cabin fever

### ISSUE THREAD

**Issue by tommargar** [Killface1980/RW_ColonistBarKF#15]
One way to improve, what is already great, would be a icon for Cabin fever, that way I would not forget to take my pawns out for a walk.

**Comment by lclpsoz** [comment]
I support this suggestion!

Didn't know _Issue tab_ could be used to make suggestions, thank you for the information.

**Comment by tommargar** [comment]
I know of only the issues, but I have tagged it as a suggesetion. I'll take care of it once I make a new batch of icons.

**Comment by lclpsoz** [comment]
Okay, thank you!

**Comment by tommargar** [comment]
added
