### ISSUE TITLE
Question: A16

### ISSUE THREAD

**Issue by ghost** [Killface1980/RW_ColonistBarKF#18]
Sorry to post this as an issue but github doesn't really have good communication tools...

Is this project ready for testing in A16? Will bug reports be of value?

**Comment by tommargar** [comment]
hi Lady-Luck,
I made an A16, version, but it's seriously broken and now crashing RW with the latest update. There's an A16 branch of this project, it might be working for you.
Bug reports are of no value right now, but thank you very much for your offer. I'll see what I can do later, really looking forward in keeping this mod alive.

**Comment by ghost** [comment]
I appreciate the time you're putting into this. It really is one of the most essential mods out there.

**Comment by tommargar** [comment]
thank you for you kind feedback. I'm also missing it, but I guess I need a way to entirely remove the vanilla bar, use my A15 code instead, and add what A16 changed (groups, UI scaling, etc.).
I also want to say sorry for my rude behavior earlier this year. I was in pain for a longer period of time and forgot myself sometimes. Won't happen again.

**Comment by tommargar** [comment]
damn, I think I'm dreaming :c) soon …
![image](https://cloud.githubusercontent.com/assets/16738568/21327824/3b932a86-c631-11e6-8902-fbfd57b6ed0c.png)

**Comment by ghost** [comment]
> I also want to say sorry for my rude behavior earlier this year. I was in pain for a longer period of time and forgot myself sometimes. Won't happen again.

I'd already forgotten.

That's some really nice progress. I notice there was a recent update. Is now a good time for me to test?

**Comment by tommargar** [comment]
Hi there, I just updated on Git. It's a working version with all the new stuff from A16 (grouping for caravans etc.). 
I tested only the basic functions, apart from the not extending group frame I'm happy. Go ahead and tell me all your findings.

**Comment by ghost** [comment]
It's a Christmas miracle!

**Comment by ghost** [comment]
Haven't had any issues thus far.
