### ISSUE TITLE
XML Error on deprecated config setting on game start

### ISSUE THREAD

**Issue by ghost** [Killface1980/RW_ColonistBarKF#20]
```
XML error: <ShowCrowded>True</ShowCrowded> doesn't correspond to any field in type SettingsColonistBar.
Verse.Log:Error(String)
Verse.XmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.XmlLoader:ItemFromXmlFile(String, Boolean)
ColonistBarKF.CBKF:LoadBarSettings(String)
ColonistBarKF.CBKF:Start()
```

Preferred behavior would be for it to ignore or silently remove config settings that have been deprecated.

**Comment by tommargar** [comment]
I don't know how to do it, and it only happens when loaded for the first time. I'll reserve renaming to major releases, as 0.16.0.

**Comment by tommargar** [comment]
can't be fixed, expect this only to happen in development or with major version updates
