### ISSUE TITLE
Not handling multi-colony multi-line display

### ISSUE THREAD

**Issue by Rock5** [Killface1980/RW_ColonistBarKF#23]
![rimworld vanilla bar](https://cloud.githubusercontent.com/assets/4830444/22264615/bf7a1c62-e2cc-11e6-8b5b-171137116f13.jpg)
![rimworld kf bar](https://cloud.githubusercontent.com/assets/4830444/22264619/c705ef42-e2cc-11e6-9653-14be70636bd2.jpg)
The top image is the vanilla bar. The bottom is the Colonist Bar KF. Note there are 4 people in the last group but they are not grouped together. Actually it looks like there is no grouping at all.

Can you fix this please?

**Comment by tommargar** [comment]
should be fixed with the A17 release.
