### ISSUE TITLE
Known Incompatibilities?

### ISSUE THREAD

**Issue by elwooha6** [Killface1980/RW_ColonistBarKF#25]
I'm having an issue where the moodbar doesn't show and when I enable pawn state icons the whole game interface breaks. I'm guessing that this is a compatibility error as it wasn't happening till I added a new chunk of mods. I'll be going over my modlist and testing to find the problem myself but thought I may as well ask if anyone else knows about any outstanding compatibility problems.

version: 0.16.2.2

**Comment by tommargar** [comment]
not that I know of. 
can you post your output_log.txt file located in RimWorldWin_Data after the error pops up again? I might find the answer there.

**Comment by elwooha6** [comment]
I'm getting an error with PSI when I use dev mode to spawn a faction base, not sure if this is a common case or not as I'm still a little new to the game. Here's a pastebin of the log. https://pastebin.com/Hp1uNWeU

After a few tests I can't seem to reproduce the UI dissappearing issue again which is odd because it was happening every time I started a new world. The only thing I did differently was restore a previous modconfig file but I only had time to do quick tests. I'll try working with it more tonight.

**Comment by tommargar** [comment]
seems like a known problem with the sort order and different pawn groups. I guess I fixed it for A17.

**Comment by elwooha6** [comment]
sounds good, I'll just use the vanilla sort order for now then and see if that fixes it.

**Comment by elwooha6** [comment]
I got the UI to disappear again, here is the log. It was too big for pastebin.

[output_log.txt](https://github.com/Killface1980/RW_ColonistBarKF/files/1024975/output_log.txt)
