### ISSUE TITLE
Mood bars don't always show at the start of a new game

### ISSUE THREAD

**Issue by ghost** [Killface1980/RW_ColonistBarKF#27]
Only started getting this issue when I switched to the Workshop version, I already tried clearing the settings. I think it was something in the May 24th commits that did it. Fixed by saving and reloading.

Easy to replicate, just start a new game with only HugsLib and Colonist Bar enabled...

---

Two asides, for some reason the background of some of the mood bars seems to turn green, but I think that might be a new feature? I'm not sure what it's supposed to be communicating, and it's visually confusing...

There's this almost transparent but not quite white background behind the colonist bar frame now and I hate it.

**Comment by tommargar** [comment]
I'll look into the mood bars not appearing instantly. thie git version is the most recent, and you'll have to wait a few seconds real time to update the stats. I did this to avoid errors with stats not initialized etc.
the turning green is the background color changing to the next mood color if below a certain percentage. it was not easy to spot which stage the pawn currently is in, and with extreme break thresholds of 1 %, some stages were not visible. give it a shot ;)
the white background was for testing purpose, as I needed a visual reference for placing the rects. will be removed.

**Comment by tommargar** [comment]
guess it's fixed with the most recent version
