### ISSUE TITLE
Bug- File write exception - custom settings folder

### ISSUE THREAD

**Issue by luis-m-gonzalez** [Killface1980/RW_ColonistBarKF#33]
Hi, thank you very much for your work

Please find the attached screenshot with the exception that is thrown whenever I load the mod for the first time.

I'm using a custom settings folder using the -savedatafolder command: 
C:\Dropbox\Dropbox\RimWorld\RimWorldWin.exe -savedatafolder=C:\Dropbox\Dropbox\rimworld

This is probably related with the bug. I tried running the game with Administrator permission, without any change - Windows 10

I used the latest committed files of he mod.

Kind Regards
<img width="961" alt="exception" src="https://user-images.githubusercontent.com/33406451/32422225-2005daa0-c26d-11e7-83af-9a83a3265955.png">

**Comment by tommargar** [comment]
Is there a folder named "Config" in your custom save folder? If not, try creating it, this should solve the problem for now.

**Comment by luis-m-gonzalez** [comment]
Hi KF,

Thanks for your quick reply. The folder was there, and surprisingly, so was the file. I googled the error code 1224 and the issue is a conflict with another process. So I turned Dropbox off and that fixes the problem.

Now the weird part, I only need to turn off Dropbox on my laptop, but it is not necessary on my desktop, even though both run Windows 10, both with administrator users.

**Comment by tommargar** [comment]
maybe your laptop is connected via wi-fi, your pc not? Unity has some weird behavior with writing files which might be blocked by Dropbox.
