### ISSUE TITLE
Background color by gender just makes the background invisible

### ISSUE THREAD

**Issue by ghost** [Killface1980/RW_ColonistBarKF#4]
Just what it says on the tin. I've tried the last two versions and the one in development and they all have this issue.

**Comment by tommargar** [comment]
can you provide me with a screenshot? do you have dev mode on? does a message pop up? can you provide me with the output_log?

**Comment by ghost** [comment]
I can certainly provide you with a screenshot, one moment. I'm not on developer mode. No message pops up. I'm not sure how to provide you with an output_log.

**Comment by ghost** [comment]
http://i.imgur.com/be4y1GN.png

**Comment by tommargar** [comment]
thanks Lady-Luck, I was able to reproduce that behaviour. you can try out https://github.com/Killface1980/RW_ColonistBarKF and see if this bug's finally fixed

**Comment by ghost** [comment]
All fixed.
